# Generated by Django 4.1.4 on 2023-01-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipedb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipename', models.CharField(max_length=50)),
                ('instraction', models.TextField(default=0)),
                ('ingredients', models.TextField(default=0)),
            ],
        ),
    ]
