# Generated by Django 4.1.4 on 2023-01-10 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeadminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipedb',
            name='image',
            field=models.ImageField(default=0, upload_to='recipe'),
        ),
    ]
