# Generated by Django 4.1.4 on 2023-01-12 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeadminApp', '0002_recipedb_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipedb',
            name='image',
            field=models.ImageField(default='null.jpg', upload_to='recipe'),
        ),
    ]
