# Generated by Django 4.1.4 on 2023-01-13 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipeuserApp', '0002_registerdb'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerdb',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
